# Generated by Django 5.2.7 on 2025-10-18 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nova', '0002_categoriecours_cours'),
    ]

    operations = [
        migrations.CreateModel(
            name='APropos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='Mon Nom', max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='apropos/')),
                ('biographie', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('video', models.FileField(blank=True, null=True, upload_to='videos/biographie/')),
            ],
        ),
        migrations.CreateModel(
            name='ParcoursAcademique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.CharField(max_length=50)),
                ('titre', models.CharField(max_length=200)),
                ('etablissement', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
