# Generated by Django 5.2.7 on 2025-10-18 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nova', '0003_apropos_parcoursacademique'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='applications/videos/'),
        ),
    ]
